package it.unitn.test.testh2.model;
// Generated 10-dic-2013 16.58.09 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tabhealthprofile generated by hbm2java
 */
public class Tabhealthprofile  implements java.io.Serializable {


     private Integer idtabhealthprofile;
     private Tabperson tabperson;
     private Date date;
     private double weight;
     private double height;
     private int steps;
     private int calories;

    public Tabhealthprofile() {
    }

    public Tabhealthprofile(Tabperson tabperson, Date date, double weight, double height, int steps, int calories) {
       this.tabperson = tabperson;
       this.date = date;
       this.weight = weight;
       this.height = height;
       this.steps = steps;
       this.calories = calories;
    }
   
    public Integer getIdtabhealthprofile() {
        return this.idtabhealthprofile;
    }
    
    public void setIdtabhealthprofile(Integer idtabhealthprofile) {
        this.idtabhealthprofile = idtabhealthprofile;
    }
    public Tabperson getTabperson() {
        return this.tabperson;
    }
    
    public void setTabperson(Tabperson tabperson) {
        this.tabperson = tabperson;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }
    public double getHeight() {
        return this.height;
    }
    
    public void setHeight(double height) {
        this.height = height;
    }
    public int getSteps() {
        return this.steps;
    }
    
    public void setSteps(int steps) {
        this.steps = steps;
    }
    public int getCalories() {
        return this.calories;
    }
    
    public void setCalories(int calories) {
        this.calories = calories;
    }




}


