package it.unitn.test.testh2.model;
// Generated 10-dic-2013 16.58.09 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tabperson generated by hbm2java
 */
public class Tabperson  implements java.io.Serializable {


     private Integer idperson;
     private String name;
     private String surname;
     private Date birthday;
     private Set tabhealthprofiles = new HashSet(0);

    public Tabperson() {
    }

	
    public Tabperson(String name, String surname, Date birthday) {
        this.name = name;
        this.surname = surname;
        this.birthday = birthday;
    }
    public Tabperson(String name, String surname, Date birthday, Set tabhealthprofiles) {
       this.name = name;
       this.surname = surname;
       this.birthday = birthday;
       this.tabhealthprofiles = tabhealthprofiles;
    }
   
    public Integer getIdperson() {
        return this.idperson;
    }
    
    public void setIdperson(Integer idperson) {
        this.idperson = idperson;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Set getTabhealthprofiles() {
        return this.tabhealthprofiles;
    }
    
    public void setTabhealthprofiles(Set tabhealthprofiles) {
        this.tabhealthprofiles = tabhealthprofiles;
    }




}


