
package it.unitn.lsde.ass3.assignment3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "soapService", targetNamespace = "http://assignment3.ass3.lsde.unitn.it/", wsdlLocation = "http://127.0.0.1:5914/ws/soap?wsdl")
public class SoapService
    extends Service
{

    private final static URL SOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICE_EXCEPTION;
    private final static QName SOAPSERVICE_QNAME = new QName("http://assignment3.ass3.lsde.unitn.it/", "soapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:5914/ws/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICE_WSDL_LOCATION = url;
        SOAPSERVICE_EXCEPTION = e;
    }

    public SoapService() {
        super(__getWsdlLocation(), SOAPSERVICE_QNAME);
    }

    public SoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICE_QNAME, features);
    }

    public SoapService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICE_QNAME);
    }

    public SoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICE_QNAME, features);
    }

    public SoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ass3Services
     */
    @WebEndpoint(name = "ServiceImplPort")
    public Ass3Services getServiceImplPort() {
        return super.getPort(new QName("http://assignment3.ass3.lsde.unitn.it/", "ServiceImplPort"), Ass3Services.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ass3Services
     */
    @WebEndpoint(name = "ServiceImplPort")
    public Ass3Services getServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://assignment3.ass3.lsde.unitn.it/", "ServiceImplPort"), Ass3Services.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICE_EXCEPTION!= null) {
            throw SOAPSERVICE_EXCEPTION;
        }
        return SOAPSERVICE_WSDL_LOCATION;
    }

}
